apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: 709973393692.dkr.ecr.us-west-2.amazonaws.com/webservergt:2.0
        ports:
        - containerPort: 80
      nodeSelector:
        disktype: service1	
